branch-defaults:
  stg-deploy:
    environment: stationfyWeb-env-stg
global:
  application_name: stationfy-web
  default_ec2_keyname: ec2-keypair
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
